### ISSUE TITLE
crash when chatting

### ISSUE THREAD

**Issue by illim** [illim/freespectrogdx#22]
bug seems to appears when chatting between english locale (use en font) and russian 

```
NetClient: net client>Handle Message(Header(Proxy,110,7,0),Some([B@219930cb))
java.lang.IndexOutOfBoundsException: index can't be >= size: 1 >= 0
	at com.badlogic.gdx.utils.Array.get(Array.java:127)
	at com.badlogic.gdx.graphics.g2d.GlyphLayout.setText(GlyphLayout.java:197)
	at com.badlogic.gdx.graphics.g2d.BitmapFontCache.addText(BitmapFontCache.java:482)
	at com.badlogic.gdx.graphics.g2d.BitmapFont.draw(BitmapFont.java:218)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField.drawText(TextField.java:345)
	at com.badlogic.gdx.scenes.scene2d.ui.TextField.draw(TextField.java:315)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:163)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:123)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:163)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.draw(Table.java:117)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.ui.WidgetGroup.draw(WidgetGroup.java:163)
	at com.badlogic.gdx.scenes.scene2d.Group.drawChildren(Group.java:110)
	at com.badlogic.gdx.scenes.scene2d.Group.draw(Group.java:57)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:128)
	at com.mygdx.game.Screens.render(Screens.scala:37)
	at com.mygdx.game.LobbyScreen.render(Screens.scala:134)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
java.lang.IllegalStateException: SpriteBatch.end must be called before begin.
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.begin(SpriteBatch.java:163)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:127)
	at com.mygdx.game.Screens.render(Screens.scala:37)
	at com.mygdx.game.LobbyScreen.render(Screens.scala:134)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
java.lang.IllegalStateException: SpriteBatch.end must be called before begin.
	at com.badlogic.gdx.graphics.g2d.SpriteBatch.begin(SpriteBatch.java:163)
	at com.badlogic.gdx.scenes.scene2d.Stage.draw(Stage.java:127)
	at com.mygdx.game.Screens.render(Screens.scala:37)
	at com.mygdx.game.LobbyScreen.render(Screens.scala:134)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

```

**Comment by prospectronet** [comment]
Fine! But if for example somebody will chat on Chinese, will he crash everybody?
